trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- script: |
    curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    az login --service-principal -u $(servicePrincipalId) -p $(servicePrincipalKey) --tenant $(tenantId)
    az account set --subscription $(subscriptionId)
    curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh
    docker run hello-world
  displayName: 'Setup Environment'
  env:
    servicePrincipalId: $(servicePrincipalId)
    servicePrincipalKey: $(servicePrincipalKey)
    tenantId: $(tenantId)
    subscriptionId: $(subscriptionId)



- script: |
    cd ../
    chmod +x ./setup.sh
    chmod +x ./deploy-monolith.sh
    ./setup.sh
    ./deploy-monolith.sh
  displayName: 'Deploy Monolith Application'

- script: |
    kubectl get service monolith
  displayName: 'Get Service IPs'
